### ISSUE TITLE
unitialized constant GitHub (NameError)

### ISSUE THREAD

**Issue by sunnyrjuneja** [dmarcotte/github-markdown-preview#35] opened 2015-01-30 19:07 UTC
Hiya,

I'm ruby 2.2.0 and I just installed github-markdown-preview using gem install. I got this stacktrace:

```
/home/wasd/.rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require': uninitialized constant GitHub (NameError)
        from /home/wasd/.rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/wasd/.gem/ruby/2.2.0/gems/html-pipeline-1.11.0/lib/html/pipeline/markdown_filter.rb:2:in `<top (required)>'
        from /home/wasd/.gem/ruby/2.2.0/gems/github-markdown-preview-3.1.3/lib/github-markdown-preview/html_preview.rb:68:in `pipeline_filters'
        from /home/wasd/.gem/ruby/2.2.0/gems/github-markdown-preview-3.1.3/lib/github-markdown-preview/html_preview.rb:41:in `initialize'
        from /home/wasd/.gem/ruby/2.2.0/gems/github-markdown-preview-3.1.3/bin/github-markdown-preview:31:in `new'
        from /home/wasd/.gem/ruby/2.2.0/gems/github-markdown-preview-3.1.3/bin/github-markdown-preview:31:in `<top (required)>'
        from /home/wasd/.gem/ruby/2.2.0/bin/github-markdown-preview:23:in `load'
        from /home/wasd/.gem/ruby/2.2.0/bin/github-markdown-preview:23:in `<main>'
```

**Comment by dmarcotte** [comment] 2015-01-31 21:53
Hey @whatasunnyday, thanks for the heads up on this.  I was able to reproduce by doing a `gem update`, and tracked the issue down to version 1.8.2 of the `json` gem (though I'm not sure yet _how_ it's interfering...).

I've fixed this (#36) and released an updated `github-markdown-preview`, so you should be another `gem update` away from being good.

NOTE: while fixing this I got myself into a weird state where I still got the error with the updated version of github-markdown-preview (3.1.4).  I cleared out my gems and reinstalled to try and troubleshoot, but then was not able to get back in the bad state, so you may need to do some uninstalling/reinstalling to right the ship.

Hopefully that gets you going.  Let me know if you're still having trouble, and thanks again for posting this.

**Comment by whatasunnyday** [comment] 2015-02-01 21:31
@dmarcotte No problem. Thanks for being so responsive.

**Comment by FernandoBasso** [comment] 2015-04-17 09:54
The problem happens for me as well with 3.1.4.

    $ github-markdown-preview data-time.md 
    /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require': uninitialized constant GitHub (NameError)
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/fernando/.gem/ruby/2.2.0/gems/html-pipeline-1.11.0/lib/html/pipeline/markdown_filter.rb:2:in `<top (required)>'
	from /home/fernando/.gem/ruby/2.2.0/gems/github-markdown-preview-3.1.4/lib/github-markdown-preview/html_preview.rb:68:in `pipeline_filters'
	from /home/fernando/.gem/ruby/2.2.0/gems/github-markdown-preview-3.1.4/lib/github-markdown-preview/html_preview.rb:41:in `initialize'
	from /home/fernando/.gem/ruby/2.2.0/gems/github-markdown-preview-3.1.4/bin/github-markdown-preview:31:in `new'
	from /home/fernando/.gem/ruby/2.2.0/gems/github-markdown-preview-3.1.4/bin/github-markdown-preview:31:in `<top (required)>'
	from /home/fernando/.gem/ruby/2.2.0/bin/github-markdown-preview:23:in `load'
	from /home/fernando/.gem/ruby/2.2.0/bin/github-markdown-preview:23:in `<main>'

**Comment by dmarcotte** [comment] 2015-04-21 20:17
Hey @FernandoBasso, thanks for the heads up that you're running into this.  Is it feasible for you to reinstall all your gems?  As I noted above, that's what ultimately got me fixed up (which is odd, but made it so I could no longer reproduce so further troubleshooting is a touch tough).

**Comment by dmcinnes** [comment] 2015-05-22 20:30
Hi FWIW I'm running into this issue as well on `ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]`

**Comment by dmarcotte** [comment] 2015-05-23 17:27
Thanks @dmcinnes.  Clearly there's still a problem lurking here... are you still in this state?  If yes, can you post the output of `gem dep github-markdown-preview` here for me?

**Comment by dmcinnes** [comment] 2015-05-28 00:43
```
$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
$ gem dep github-markdown-preview
Gem github-markdown-preview-3.1.4
  bundler (~> 1.7, development)
  gemoji (~> 2.1)
  github-markdown (~> 0.6)
  html-pipeline (~> 1.11)
  json (= 1.8.1)
  listen (= 2.8)
  minitest (~> 5.4, development)
  rake (~> 10.3, development)
  sanitize (~> 3.0)
```

Also it's working for me on ruby 2.2.1p85
```
$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
$ gem dep github-markdown-preview
Gem github-markdown-preview-3.1.4
  bundler (~> 1.7, development)
  gemoji (~> 2.1)
  github-markdown (~> 0.6)
  html-pipeline (~> 1.11)
  json (= 1.8.1)
  listen (= 2.8)
  minitest (~> 5.4, development)
  rake (~> 10.3, development)
  sanitize (~> 3.0)
```

**Comment by dmarcotte** [comment] 2015-05-28 19:47
Thanks @dmcinnes!  So odd that with identical deps this behaves differently.  Trying to think of what to try next... can you share the output of `gem list` for both those rubies?

**Comment by dmcinnes** [comment] 2015-05-29 23:12
Sure!

DOESN'T WORK:
```
$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
$ gem list

*** LOCAL GEMS ***

activerecord (2.3.17)
activerecord2-hstore (1.0.6)
activesupport (4.2.1, 2.3.17)
addressable (2.3.8, 2.3.6)
api-admin (0.3.44)
artifice-excon (0.1.4)
atomic (1.0.1)
aws-sdk-core (2.0.41, 2.0.18)
backports (3.6.4)
bcrypt-ruby (3.0.1)
bigdecimal (1.2.6)
binding_of_caller (0.7.2)
builder (3.2.2)
bundler (1.9.4)
byebug (4.0.5, 2.7.0)
caas-api (0.2.2)
celluloid (0.16.0)
clamp (0.6.5)
clandestined (1.0.0rc1)
clockwork (0.2.3)
coderay (1.1.0)
columnize (0.9.0, 0.8.9)
committee (1.7.3, 1.2.0)
connection_pool (0.9.3)
crack (0.4.2)
crass (1.0.2)
database_cleaner (1.4.1, 1.0.1)
debug_inspector (0.0.2)
debugger-linecache (1.2.0)
diff-lcs (1.2.5)
docile (1.1.5)
domain_name (0.5.24)
dotenv (2.0.1, 1.0.2, 0.8.0)
erubis (2.7.0)
excon (0.45.2, 0.38.0)
factory_girl (2.6.4)
fakeredis (0.5.0)
faraday (0.8.4)
fast_stack (0.1.0)
fernet (2.1)
ffi (1.9.6)
flamegraph (0.1.0)
fog (1.23.0)
fog-brightbox (0.7.1)
fog-core (1.27.3)
fog-json (1.0.0)
fog-softlayer (0.3.30)
foreman (0.63.0)
formatador (0.2.5)
gemoji (2.1.0)
github-markdown (0.6.8)
github-markdown-preview (3.1.4)
global_phone (1.0.1)
guard (2.8.2)
guard-rspec (4.3.1)
heroku-api (0.3.23)
hitimes (1.2.2)
html-pipeline (1.11.0)
http-cookie (1.0.2)
http_accept (0.1.6)
i18n (0.7.0, 0.6.9)
iconv (1.0.4)
inflecto (0.0.2)
io-console (0.4.3)
ion-api (0.1.13)
ion-client (0.2.97)
ipaddress (0.8.0)
jmespath (1.0.2)
json (1.8.1)
json-schema (2.2.4)
json_schema (0.6.0, 0.3.1)
jwt (1.5.0)
kch-dominion (1.0.0)
kgio (2.9.2)
launchy (2.4.3)
legacy-fernet (1.6.3)
listen (2.8.0)
logplex-client (0.1.10)
lumberjack (1.0.9)
machinist (2.0)
mail (2.6.1)
mechanize (2.7.3)
method_source (0.8.2)
mime-types (2.5, 2.4.3)
mini_portile (0.6.2)
minitest (5.6.1, 5.4.3, 2.12.1)
moargration (0.0.5)
multi_json (1.11.0, 1.7.7)
multi_xml (0.5.5)
multipart-post (1.1.5)
net-http-digest_auth (1.4)
net-http-persistent (2.9.4)
net-scp (1.2.1)
net-ssh (2.9.2)
netrc (0.10.3, 0.7.7)
nokogiri (1.6.5)
nokogumbo (1.2.0)
ntlm-http (0.1.1)
oj (2.12.5, 2.1.4)
pg (0.18.1, 0.15.1)
pliny (0.8.2)
pony (1.9)
power_assert (0.2.3, 0.2.2)
prmd (0.7.3, 0.7.0)
pry (0.10.1, 0.9.12.6)
pry-byebug (3.1.0, 1.3.2)
pry-stack_explorer (0.4.9.1)
psych (2.0.8)
public_suffix (1.4.6)
puma (2.11.2)
purdytest (1.0.0)
que (0.10.0)
queue_classic (2.1.4)
rack (1.6.1, 1.6.0, 1.5.2)
rack-protection (1.5.3)
rack-ssl (1.4.1)
rack-test (0.6.3, 0.6.2)
rack-timeout (0.2.4)
raindrops (0.13.0)
rake (10.4.2, 10.3.2, 10.1.1)
rake-compiler (0.9.5)
rb-fsevent (0.9.4)
rb-inotify (0.9.5)
rdoc (4.2.0)
redis (3.2.1, 3.0.2)
relishable (0.31)
rest-client (1.8.0, 1.6.7)
rollbar (1.5.1)
rotp (1.6.1)
rr (1.1.2)
rspec (3.2.0, 3.1.0)
rspec-core (3.2.3, 3.1.7)
rspec-expectations (3.2.1, 3.1.2)
rspec-mocks (3.2.1, 3.1.3)
rspec-support (3.2.2, 3.1.2)
ruby-openid (2.1.8)
safe_yaml (1.0.4)
sanitize (3.1.2)
scrolls (0.3.8)
sequel (4.22.0, 4.21.0, 3.41.0)
sequel_pg (1.6.9)
simplecov (0.10.0, 0.9.2)
simplecov-html (0.10.0, 0.9.0)
simplecov-rcov (0.2.3)
simpleidn (0.0.4)
sinatra (1.4.6, 1.4.5)
sinatra-contrib (1.4.2)
sinatra-router (0.2.3)
slop (3.6.0)
sshkey (1.6.1)
stackprof (0.2.7)
sucker_punch (1.4.0)
term-ansicolor (1.3.0, 1.0.7)
test-unit (3.0.9, 3.0.8)
thor (0.19.1)
thread_safe (0.3.5)
tilt (1.4.1)
timecop (0.3.5)
timers (4.0.1)
tins (1.5.1)
tzinfo (1.2.2)
umbrella-auth (0.0.3)
unf (0.1.4)
unf_ext (0.0.7.1)
unicorn (4.4.0)
valcro (0.1)
webmock (1.20.4)
webrobots (0.1.1)
yajl-ruby (1.1.0)
zeus (0.15.4)
```

WORKS:
```
$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
$ gem list

*** LOCAL GEMS ***

activerecord (2.3.17)
activerecord2-hstore (1.0.6)
activesupport (2.3.17)
addressable (2.3.8, 2.3.6)
api-admin (0.3.47, 0.3.46, 0.3.43, 0.3.39)
artifice-excon (0.1.4)
atomic (1.0.1)
aws-sdk-core (2.0.30, 2.0.29, 2.0.18)
backports (3.6.4, 3.6.3)
bcrypt-ruby (3.0.1)
bigdecimal (1.2.6)
binding_of_caller (0.7.2)
bourbon (4.0.2)
builder (3.2.2)
bundler (1.8.4)
byebug (2.7.0)
caas-api (0.2.2)
celluloid (0.16.0)
clamp (0.6.5, 0.6.4, 0.6.3)
clandestined (1.0.0rc1)
clockwork (0.2.3)
coderay (1.1.0)
coffee-script (2.3.0)
coffee-script-source (1.8.0)
columnize (0.8.9)
committee (1.2.0)
connection_pool (0.9.3)
crack (0.4.2)
crass (1.0.2)
database_cleaner (1.0.1)
debug_inspector (0.0.2)
debugger-linecache (1.2.0)
diff-lcs (1.2.5)
docile (1.1.5)
domain_name (0.5.24, 0.5.23)
dotenv (2.0.0, 0.8.0)
dropbox-sdk (1.6.4)
erubis (2.7.0)
eventmachine (1.0.4)
excon (0.45.3, 0.45.2, 0.45.1, 0.44.4, 0.44.1)
execjs (2.2.2)
factory_girl (2.6.4)
faraday (0.9.1, 0.8.4)
fernet (2.1, 1.5)
ffi (1.9.6)
fog (1.23.0)
fog-brightbox (0.7.1)
fog-core (1.27.3)
fog-json (1.0.0)
fog-softlayer (0.3.30)
foreman (0.78.0, 0.63.0)
formatador (0.2.5)
gemoji (2.1.0)
github-markdown (0.6.8)
github-markdown-preview (3.1.4)
global_phone (1.0.1)
guard (2.8.2)
guard-rspec (4.3.1)
heroku-api (0.3.23, 0.3.22)
highline (1.6.21)
hike (1.2.1)
hitimes (1.2.2)
honeybadger (1.8.0)
html-pipeline (1.11.0)
http-cookie (1.0.2)
http_accept (0.1.6)
i18n (0.6.9)
iconv (1.0.4)
inflecto (0.0.2)
io-console (0.4.3)
ion-api (0.1.13)
ion-client (0.2.97, 0.2.96, 0.2.84)
ipaddress (0.8.0)
jmespath (1.0.2)
json (1.8.2, 1.8.1)
json_schema (0.3.1)
kch-dominion (1.0.0)
kgio (2.9.2)
launchy (2.4.3)
legacy-fernet (1.6.3)
listen (2.8.0)
lock-smith (1.0.0, 0.0.5)
logplex-client (0.1.10)
lumberjack (1.0.9)
machinist (2.0)
mail (2.6.3, 2.6.1)
mechanize (2.7.3)
method_source (0.8.2)
mime-types (2.5, 2.4.3)
mini_portile (0.6.2)
minitest (5.4.3, 2.12.1)
moargration (0.0.5)
multi_json (1.11.0, 1.10.1, 1.7.7)
multi_xml (0.5.5)
multipart-post (2.0.0, 1.1.5)
net-http-digest_auth (1.4)
net-http-persistent (2.9.4)
net-scp (1.2.1)
net-ssh (2.9.2)
netrc (0.10.3)
nokogiri (1.6.6.2, 1.6.5)
nokogumbo (1.2.0)
ntlm-http (0.1.1)
octokit (3.8.0)
oj (2.1.4, 2.0.0)
open4 (1.3.0)
pg (0.18.2, 0.18.1, 0.15.1)
Platform (0.4.0)
pony (1.11, 1.9)
POpen4 (0.1.4)
power_assert (0.2.2)
prmd (0.7.0)
pry (0.9.12.6)
pry-byebug (1.3.2)
pry-stack_explorer (0.4.9.1)
psych (2.0.8)
public_suffix (1.4.6)
puma (1.6.3)
purdytest (1.0.0)
que (0.10.0)
queue_classic (2.1.4)
rack (1.5.2)
rack-flash3 (1.0.3)
rack-instruments (0.3.2)
rack-protection (1.5.3, 1.3.2)
rack-ssl (1.3.2)
rack-test (0.6.2)
rack_csrf (2.4.0)
raindrops (0.13.0)
rake (10.4.2, 10.1.1, 0.9.2.2)
rb-fsevent (0.9.4)
rb-inotify (0.9.5)
rdiscount (2.1.8)
rdoc (4.2.0)
redis (3.0.2)
relishable (0.31)
rest-client (1.8.0, 1.7.2, 1.6.7)
rollbar (1.5.1)
rotp (1.6.1)
rr (1.1.2, 1.0.4)
rspec (3.2.0, 3.1.0)
rspec-core (3.2.1, 3.1.7)
rspec-expectations (3.2.0, 3.1.2)
rspec-mocks (3.2.1, 3.1.3)
rspec-support (3.2.2, 3.1.2)
ruby-openid (2.1.8)
safe_yaml (1.0.4)
sanitize (3.1.2)
sass (3.4.7)
sawyer (0.6.0)
scrolls (0.3.8)
sequel (3.41.0)
sequel_pg (1.6.9)
simplecov (0.9.2)
simplecov-html (0.9.0)
simplecov-rcov (0.2.3)
simpleidn (0.0.4)
sinatra (1.4.5, 1.3.3)
sinatra-contrib (1.4.2, 1.3.2)
sinatra-router (0.2.3, 0.2.0)
slides (0.2.0)
slim (1.3.5)
slop (3.6.0)
spinning_cursor (0.3.0)
sprockets (2.8.1)
sprockets-sass (1.0.1)
sshkey (1.7.0, 1.6.1)
temple (0.5.5)
term-ansicolor (1.3.0, 1.0.7)
test-unit (3.0.8)
thor (0.19.1)
tilt (1.4.1, 1.3.3)
timecop (0.3.5)
timers (4.0.1)
tins (1.5.1, 1.3.5, 1.3.4)
unf (0.1.4)
unf_ext (0.0.7.1, 0.0.6)
unicorn (4.4.0)
valcro (0.1)
webmock (1.20.4, 1.18.0)
webrobots (0.1.1)
yajl-ruby (1.1.0)
yui-compressor (0.9.6)
zeus (0.15.4)
```

**Comment by dmarcotte** [comment] 2015-05-31 17:46
Much appreciated @dmcinnes.  Hopefully I'll be able to boil this down to the problem...

**Comment by cseelus** [comment] 2015-07-31 19:30
Same problem here on OSX 10.10.4 with Ruby 2.2.2p95.

Output:
```
$ github-markdown-preview README.md 
D, [2015-07-31T21:29:02.053462 #89941] DEBUG -- : Celluloid 0.17.0 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require': uninitialized constant GitHub (NameError)
	from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/lib/html/pipeline/markdown_filter.rb:2:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/github-markdown-preview-3.1.4/lib/github-markdown-preview/html_preview.rb:68:in `pipeline_filters'
	from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/github-markdown-preview-3.1.4/lib/github-markdown-preview/html_preview.rb:41:in `initialize'
	from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/github-markdown-preview-3.1.4/bin/github-markdown-preview:31:in `new'
	from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/github-markdown-preview-3.1.4/bin/github-markdown-preview:31:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.2.2/bin/github-markdown-preview:23:in `load'
	from /usr/local/var/rbenv/versions/2.2.2/bin/github-markdown-preview:23:in `<main>'
$ gem list

*** LOCAL GEMS ***

actionmailer (4.2.3)
actionpack (4.2.3)
actionview (4.2.3)
activejob (4.2.3)
activemodel (4.2.3)
activerecord (4.2.3)
activesupport (4.2.3)
addressable (2.3.8)
ansi (1.5.0)
arel (6.0.2)
autoprefixer-rails (5.2.1.1)
awesome_print (1.6.1)
aws-sdk (1.64.0)
aws-sdk-v1 (1.64.0)
bcrypt (3.1.10)
bigdecimal (1.2.6)
binding_of_caller (0.7.2)
bootstrap-sass (3.3.5.1)
bootstrap-will_paginate (0.0.10)
bourbon (4.2.3)
builder (3.2.2)
bundler (1.10.6)
byebug (5.0.0)
capybara (2.4.4)
capybara-email (2.4.0)
capybara-screenshot (1.0.11)
carrierwave (0.10.0)
carrierwave-aws (0.5.0)
celluloid (0.17.0)
celluloid-essentials (0.20.1.1)
celluloid-extras (0.20.0)
celluloid-fsm (0.20.0)
celluloid-pool (0.20.0)
celluloid-supervision (0.20.0)
choice (0.2.0)
cliver (0.3.2)
coderay (1.1.0)
coffee-rails (4.1.0)
coffee-script (2.4.1)
coffee-script-source (1.9.1.1)
columnize (0.9.0)
crass (1.0.2)
debug_inspector (0.0.2)
devise (3.5.1)
dotenv (2.0.2)
em-websocket (0.5.1)
erubis (2.7.0)
eventmachine (1.0.7)
execjs (2.5.2)
ffi (1.9.10)
figaro (1.1.1)
font-awesome-rails (4.3.0.0)
foreman (0.78.0)
formatador (0.2.5)
gemoji (2.1.0)
github-markdown (0.6.8)
github-markdown-preview (3.1.4)
globalid (0.3.5)
guard (2.13.0)
guard-livereload (2.4.0)
hitimes (1.2.2)
html-pipeline (1.11.0)
http_parser.rb (0.6.0)
i18n (0.7.0)
io-console (0.4.3)
jbuilder (2.3.1)
jquery-rails (4.0.4)
json (1.8.3, 1.8.1)
launchy (2.4.3)
listen (3.0.3, 2.8.0)
loofah (2.0.2)
lumberjack (1.0.9)
mail (2.6.3)
method_source (0.8.2)
mime-types (2.6.1)
mini_magick (4.2.7)
mini_portile (0.6.2)
minitest (5.7.0, 5.4.3)
minitest-capybara (0.7.2)
minitest-metadata (0.5.3)
minitest-rails (2.2.0)
minitest-rails-capybara (2.1.1)
minitest-reporters (1.0.5)
multi_json (1.11.2)
nenv (0.2.0)
nokogiri (1.6.6.2)
nokogumbo (1.2.0)
notiffany (0.0.7)
orm_adapter (0.5.0)
pg (0.18.2)
poltergeist (1.6.0)
power_assert (0.2.2)
pry (0.10.1)
pry-rails (0.3.4)
psych (2.0.8)
puma (2.11.3)
rack (1.6.4)
rack-livereload (0.3.16)
rack-test (0.6.3)
rails (4.2.3)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.6)
rails-erd (1.4.1)
rails-html-sanitizer (1.0.2)
rails-i18n (4.0.4)
rails_12factor (0.0.3)
rails_serve_static_assets (0.0.4)
rails_stdout_logging (0.0.3)
railties (4.2.3)
rake (10.4.2)
rb-fsevent (0.9.5)
rb-inotify (0.9.5)
rdoc (4.2.0)
responders (2.1.0)
rspec-logsplit (0.1.3)
ruby-graphviz (1.2.2)
ruby-progressbar (1.7.5)
sanitize (3.1.2)
sass (3.4.16)
sass-rails (5.0.3)
sdoc (0.4.1)
shellany (0.0.1)
shoulda (3.5.0)
shoulda-context (1.2.1)
shoulda-matchers (2.8.0)
slim (3.0.6)
slim-rails (3.0.1)
slop (3.6.0)
spring (1.3.6)
sprockets (3.2.0)
sprockets-rails (2.3.2)
temple (0.7.6)
test-unit (3.0.8)
thor (0.19.1)
thread_safe (0.3.5)
tilt (1.4.1)
timers (4.0.1)
tzinfo (1.2.2)
uglifier (2.7.1)
warden (1.2.3)
web-console (2.2.1)
websocket-driver (0.6.2)
websocket-extensions (0.1.2)
wicked (1.1.1)
wicked_pdf (0.11.0)
will_paginate (3.0.7)
wkhtmltopdf-binary-edge (0.12.2.1)
wkhtmltopdf-heroku (2.12.2.4)
xpath (2.0.0)
```

**Comment by dmarcotte** [comment] 2015-08-02 22:31
Thanks @cseelus.  This is still a mystery: even installing gems in such a way that my `gem list` was almost identical to @dmcinnes (save for some gems which are apparently not hosted on Rubygems) did not get me reproducing.

I just updated the dependencies in #39 and released `4.0.0`.  @dmcinnes, @cseelus can you let me know if updating to `4.0.0` gets past this error?

**Comment by cseelus** [comment] 2015-08-03 19:32
Thanks for updating. Unfortunately I still get the same error:

```
$ gem install github-markdown-preview
Fetching: nokogiri-1.6.5.gem (100%)
Building native extensions.  This could take a while...
Successfully installed nokogiri-1.6.5
Fetching: nokogumbo-1.4.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed nokogumbo-1.4.1
Fetching: sanitize-4.0.0.gem (100%)
Successfully installed sanitize-4.0.0
Fetching: html-pipeline-2.0.gem (100%)
-------------------------------------------------
Thank you for installing html-pipeline!
You must bundle Filter gem dependencies.
See html-pipeline README.md for more details.
https://github.com/jch/html-pipeline#dependencies
-------------------------------------------------
Successfully installed html-pipeline-2.0
Fetching: github-markdown-preview-4.0.0.gem (100%)
Successfully installed github-markdown-preview-4.0.0
5 gems installed
```

```
$ github-markdown-preview README.md 
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require': uninitialized constant GitHub (NameError)
	from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/html-pipeline-2.0/lib/html/pipeline/markdown_filter.rb:2:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/github-markdown-preview-4.0.0/lib/github-markdown-preview/html_preview.rb:68:in `pipeline_filters'
	from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/github-markdown-preview-4.0.0/lib/github-markdown-preview/html_preview.rb:41:in `initialize'
	from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/github-markdown-preview-4.0.0/bin/github-markdown-preview:31:in `new'
	from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/github-markdown-preview-4.0.0/bin/github-markdown-preview:31:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.2.2/bin/github-markdown-preview:23:in `load'
	from /usr/local/var/rbenv/versions/2.2.2/bin/github-markdown-preview:23:in `<main>'
```

**Comment by dmarcotte** [comment] 2015-08-03 23:11
Argh... thanks for trying.  This really has me flummoxed.

If anyone that is currently in this state is feeling enterprising, it would be really helpful to try and boil this down some.  A couple of potential things to try:
* is it possible to make a simple script which includes `github-markdown` [the way html-pipeline does](https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/markdown_filter.rb#L2) and get this error by trying to reference the `Github` constant?)
* is there a simple set of gems that can be reinstalled to fix this?  I was clearly wrong about the json gem being culprit, but since re-installing everything fixes things, there must be a culprit or two in there somewhere.  Maybe retrying github-markdown is an option?  Something else?)

For anyone just looking to work around this, so far only the nuclear option has worked reliably: reinstall all your gems (or, for rvm users, empty your gemset)

**Comment by pmueller** [comment] 2015-11-30 21:10
I was getting this error as well. 
```
OS X 10.11.1
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
github-markdown-preview-4.0.0
```

I tried loading `github-markdown` in a test script the same way as `html-pipeline` and ended up with the same `uninitialized constant Github` error. The error would also occur if I tried to `require "github/markdown"` normally without a `begin/rescue` block.

Tried re-installing the following gems: `json`, `github-markdown`, `html-pipeline` - but none of these seemed to help.

Tried downgrading `github-markdown-preview` to 3.1.4, and got a different error (thrown by `html-pipeline`): `Missing dependency 'gemoji' for EmojiFilter. See README.md for details.` Despite the fact that I had `gemoji` installed
```
$ gem list | grep gemoji
gemoji (2.1.0)
```

However, when I upgraded `github-markdown-preview` back up to 4.0.0 it started working. My test script that just requires github-markdown still gets the uninitialized constant error, so I'm not sure what changed.

Hopefully this info helps

**Comment by dmarcotte** [comment] 2015-12-04 19:06
Hey thanks @pmueller.  That really helps.  It's encouraging to know this isn't strictly a github-markdown-preview issue.  But of course it's unfortunate the core dependency problem is still completely baffling.  

So odd that seemingly random installs/reinstalls/downgrades/upgrades fix the problem (or mostly fix the problem in your case).  I hope we figure this out at some point... I'm incredibly curious about what the root cause could possibly be.

**Comment by dmcinnes** [comment] 2016-01-15 17:54
Hey FWIW I just installed this on Ruby 2.3.0 and it works.

**Comment by fledman** [comment] 2016-11-04 22:12
@dmarcotte 
I ran into this issue, and I believe that I have figured out the root cause.

If rubygems is in a state with zero unresolved dependencies, it just uses the [built-in ruby require:](https://github.com/rubygems/rubygems/blob/2.4/lib/rubygems/core_ext/kernel_require.rb#L49-L55)
```ruby
if Gem::Specification.unresolved_deps.empty? then
  RUBYGEMS_ACTIVATION_MONITOR.exit
  return gem_original_require(path)
end
```
This is the normal state when you boot IRB:
```
➜ irb
2.2.3 :001 > Gem::Specification.unresolved_deps
 => {}
```
However, after requiring this gem, `unresolved_deps` is non-empty. This is because rubygems also considers development dependencies.
```ruby
2.2.3 :002 > require 'github-markdown-preview'
 => true 
2.2.3 :003 > Gem::Specification.unresolved_deps.each{ |d| puts d.inspect };0
["json", <Gem::Dependency type=:runtime name="json" requirements=">= 1.7.7, ~> 1.7">]
["thread_safe", <Gem::Dependency type=:runtime name="thread_safe" requirements=">= 0.3.4, ~> 0.1, ~> 0.3">]
["minitest", <Gem::Dependency type=:runtime name="minitest" requirements="~> 5.1">]
 => 0 
```
This forces rubygems to use the `Gem::Specification`s to find the file path:
```ruby
spec = Gem::Specification.stubs.find { |s|
  s.activated? and s.contains_requirable_file? path
}
```
In general, this should be fine; the gemspecs should contain the correct path information.

However, in November 2014, as part of a performance optimization, rubygems [changed the code to use the full file path, instead of the relative path](https://github.com/rubygems/rubygems/commit/e2935c85fc62594ccd567c8facd46ddbd01ad100).
```ruby
begin
  RUBYGEMS_ACTIVATION_MONITOR.exit
  return gem_original_require(spec.to_fullpath(path) || path)
end if spec
```
Unfortunately, there was a bug in the method to compute the full path:
```ruby
# inside def to_fullpath(path)
fullpath = nil
suffixes = Gem.suffixes
full_require_paths.find do |dir|
  suffixes.find do |suf|
    File.file? (fullpath = "#{dir}/#{path}#{suf}")
  end
end ? fullpath : nil
```
Namely, that it doesn't properly handle cases with C extensions (because they have multiple valid paths).

The `github/markdown` gem falls into this scenario:
```
spec.full_require_paths.each do |p|
  Gem.suffixes.each do |s|
    fullpath = "#{p}/github/markdown#{s}"
    puts fullpath if File.file?(fullpath)
  end
end
/Users/davidfeldman/.rvm/gems/ruby-2.2.3/extensions/x86_64-darwin-14/2.2.0-static/github-markdown-0.6.8/github/markdown.bundle
/Users/davidfeldman/.rvm/gems/ruby-2.2.3/gems/github-markdown-0.6.8/lib/github/markdown.rb
/Users/davidfeldman/.rvm/gems/ruby-2.2.3/gems/github-markdown-0.6.8/lib/github/markdown.bundle
```
So rubygems chooses the first one, which is not actually requirable by itself:
```ruby
> gem_original_require "/Users/davidfeldman/.rvm/gems/ruby-2.2.3/extensions/x86_64-darwin-14/2.2.0-static/github-markdown-0.6.8/github/markdown.bundle" 
NameError: uninitialized constant GitHub
	from (irb):26:in `require'
```
And that is where our mysterious error comes from!

Fortunately, this bug was [fixed](https://github.com/rubygems/rubygems/commit/f58dd5a35f3fc053bbf8e5fe6482ac08ebea4063) at the end of May 2015:
```diff
-      return gem_original_require(spec.to_fullpath(path) || path)
+      return gem_original_require(path)
```
So this explains the inconsistency: only certain versions of rubygems will experience the issue.

As for solutions, you could just force people to upgrade (or downgrade, I suppose) their rubygems. However, I believe that there is a simpler and more elegant way.

Namely, if you explicitly require `github/markdown.rb`  (as opposed to `github/markdown`) it will not match on the extension's .bundle file.

It needs to happen before `HTML::Pipeline::MarkdownFilter` gets loaded, so I would place the require at the top of [lib/github-markdown-preview/html_preview.rb](https://github.com/dmarcotte/github-markdown-preview/blob/master/lib/github-markdown-preview/html_preview.rb):
```ruby
require 'listen'
require 'github/markdown.rb'
require 'html/pipeline'
```

**Comment by dmarcotte** [comment] 2016-11-04 23:44
Holy wow, thanks @fledman!  Great analysis, and such a relief to have this mystery solved.

And your proposed solution looks good too (maybe with a comment explaining why we're doing the require there, with the .rb?).  Want to send along a pull request?  I'd be glad to merge it.

**Comment by dmarcotte** [comment] 2016-11-07 20:53
Fixed in https://github.com/dmarcotte/github-markdown-preview/pull/44.  Thanks again @fledman!

**Closed by dmarcotte** 2016-11-07 20:53 UTC
